In [1]:
# Extract Sub-Array

import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix:")
print(matrix)

sub_array = matrix[0:2, 1:3]

print("Sub-array:")
print(sub_array)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub-array:
[[2 3]
 [5 6]]
