In [1]:
# Extract Rows and Columns from Matrix
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix:")
print(matrix)

# Extract row
print("First row:", matrix[0])

# Extract column
print("Second column:", matrix[:, 1])

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
Second column: [2 5 8]
