In [1]:
# Generating Random Matrix

import numpy as np
import random

random_matrix = np.random.randint(1, 10, (3, 3))

print("Random Matrix:\n", random_matrix)

Random Matrix:
 [[6 2 2]
 [9 8 7]
 [4 4 2]]
