In [5]:
# Matrix Addition

import numpy as np
 
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = A + B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition Result:\n", result)

# Matrix Substraction

result = A - B

print("Subtraction Result:\n", result)

# Matrix Multiplication

result = np.dot(A, B)

print("Matrix Multiplication Result:\n", result)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Addition Result:
 [[ 6  8]
 [10 12]]
Subtraction Result:
 [[-4 -4]
 [-4 -4]]
Matrix Multiplication Result:
 [[19 22]
 [43 50]]
